### ISSUE TITLE
wrong_transaction error

### ISSUE THREAD

**Issue by henry-hz** [burmajam/gen_aggregate#1]
Dear @burmajam , pls, review this result, seems that I am following the correct way, but still getting wrong transaction error. I noticed that you buffer requests before processing. Erlang automatically buffer messages in the "mailbox", so pls, let me understand the use case where buffering is necessary.

![gen_aggregate](https://cloud.githubusercontent.com/assets/1010008/19144983/6299eb12-8bb5-11e6-9d91-0144e42c88d8.png)

**Comment by henry-hz** [comment]
ooh... I forgot to start_link(2000), got it.
Anyway, the question is still relevant "I noticed that you buffer requests before processing. Erlang automatically buffer messages in the "mailbox", so pls, let me understand the use case where buffering is necessary."

Another question, if you block new commands when the first command was sent, and only receive new commands after commit, why in fact you don't do the commit automatically, from the gen_aggregate itself instead of waiting a new message from outside to send a commit ?

**Comment by burmajam** [comment]
Hi Henry,

Reason for buffering is that when command is sent to aggregate it just produces events with current state and returns them WITHOUT mutation. Those events are then persisted perhaps and if that was successful then they are applied on aggregate (Aggregate mutate then).

Problem is if in the meantime (between return of events and sending commit message) new message arrives to aggregate. It will be processed with wrong state (since "transaction" is in progress). In that period (between calling command and committing events) I'm blocking message processing (hence tagged tuple {:block, _, _, _}), buffering incoming messages and processing them after current transaction is committed or rolled back because of timeout (Default timeout is 2sec between return of events and commit of that transaction).

If you have more questions please don't hesitate to ask.

**Comment by henry-hz** [comment]
Thanks for the answer. Yes, I do, based on this book: https://www.microsoft.com/en-us/download/details.aspx?id=34774  , on page 24, and 25, transactions on aggregates make sense in the first two cases, but do you think that using a process manager, where every state change is intermediately written, we should also buffer  and lock ?

**Comment by burmajam** [comment]
When using process managers I wouldn't use buffers and locks. The only reason for using it here is implementation of GenServers. They don't have selective receive as you can have with manual receive..do block where you can pattern match incoming messages and rest of them can wait in inbox. I've been looking around for that scenario some time and found out that the only way to do that is manually using buffer.

**Comment by henry-hz** [comment]
Yep, makes sense, many thanks for the follow up.
